Use str::parse() instead of u16::from_str_radix()
Error:   --> src/parser.rs:82:5
   |
82 |     u16::from_str_radix(input, 10)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `input.parse::<u16>()`
   |
   = note: `-D clippy::from-str-radix-10` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_str_radix_10